KERNEL_SRC=$1

KERNEL_OUT=$2

TARGET_ARCH=$3

KERNEL_BIN_PATH=$4

KERNEL_TYPE=$5

KERNEL_CONFIG=$6

CROSS_COMPILE=$7

OUT_DIR=$8

FINAL_KERNEL=$9

THREADS_NUM=$[$(nproc) + 1]

TARGET_PREBUILT_INT_KERNEL=$KERNEL_OUT/$KERNEL_BIN_PATH/$KERNEL_TYPE



make -C $KERNEL_SRC O=$KERNEL_OUT ARCH=$TARGET_ARCH CROSS_COMPILE=$CROSS_COMPILE $KERNEL_CONFIG

make -j$THREADS_NUM -C $KERNEL_SRC O=$KERNEL_OUT ARCH=$TARGET_ARCH CROSS_COMPILE=$CROSS_COMPILE $KERNEL_TYPE

if [ $FINAL_KERNEL == "0" ]
then
make -j$THREADS_NUM -C $KERNEL_SRC O=$KERNEL_OUT ARCH=$TARGET_ARCH CROSS_COMPILE=$CROSS_COMPILE modules
fi

if [ $FINAL_KERNEL == "1" ]
then
cp $TARGET_PREBUILT_INT_KERNEL $OUT_DIR/kernel
fi






